### PR TITLE
Add support rails 7.1

### PR DESCRIPTION
**Pull request by hatsu38**
Thank you for your contribution!

Check the following boxes:

- [x] Wrote [good commit messages][1].
- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new 
  code introduces user-observable changes.
- [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://chris.beams.io/posts/git-commit/

#1442

### CODE REVIEW

**Comment by t27duck** [comment]
Think it's probably worth eliminating the deprecation warning that's being tossed up for every test in the 7.1 action?

```
DEPRECATION WARNING: TestFixtures.fixture_path= is deprecated and will be removed in Rails 7.2. Use .fixture_paths= instead.
```

**Comment by schinery** [comment]
Any action on the PR? Is it waiting for something to be done for [this](https://github.com/paper-trail-gem/paper_trail/pull/1443#issuecomment-1749757710)?

**Comment by chrisyuska** [comment]
I built off this PR and opened a new one here with deprecations fixed and Ruby 3.2 added to the testing matrix: https://github.com/paper-trail-gem/paper_trail/pull/1445

**Comment by schinery** [comment]
Looks like this is good to go, any chance of merging it and releasing to unblock upgrading to Rails 7.1? 🙏🏻

**Comment by eis-ioki** [comment]
Looks good! I am interested in getting a new release as well! Although, for now, since all the tests pass here, I am confident enough to update rails despite the warning.

**Comment by jaredbeck** [comment]
Thanks for the contribution, @hatsu38 :heart:

**Pull request merged**
