### PR TITLE
Remove references to issues

### PR DESCRIPTION
**Pull request by diachini**
With GitHub issues being turned off on the repository, there were a couple things that I felt were probably worth cleaning up:
- References to specific issues in the README & code were removed to avoid 404s
- Issue templates were removed since they are unable to be used
- Guidance for users to create issues was removed (and changed to "Go to StackOverflow" where it made sense)

----

Check the following boxes:

- [X] Wrote [good commit messages][1].
- [X] Feature branch is up-to-date with `master` (if not - rebase it).
- [X] Squashed related commits together.
- [ ] Added tests.
- [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new 
  code introduces user-observable changes.
- [ ] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by jaredbeck** [comment]
Thanks Danny, we're still discussing how to handle issues going forward. They may be re-enabled.

**Comment by DanielHeath** [comment]
Were the old issues archived anywhere? I'm trying to debug an issue that might have been mentioned there.

**Comment by diachini** [comment]
From [GitHub Help](https://help.github.com/en/articles/disabling-issues)

>If you decide to enable issues again in the future, any issues that were previously added will be available.

**Comment by jaredbeck** [comment]
The PT team has not made a decision yet about accepting new issues. In the meantime, I've contacted GH support and asked them to show our old issues, read-only.

**Comment by jaredbeck** [comment]
My conversation with GH support:

>> I had to temporarily disable the creation of issues .. However, people still need to be able to see old issues.
>>
> I'm afraid it's not possible to show old issues whilst disabling the creation of new issues, sorry!

It does not appear that GH is interested offering this feature. If you disagree with GH's decision, please contact support and let them know.

**Comment by localhostdotdev** [comment]
thought it was easy but looked into it and the easiest option would be to have a bot/app (may need a webhook too) running that is either a collaborator or has a personal token (quite very annoying)

**Comment by gammons** [comment]
it's a shame that issues have been disabled.  That seems like using a big hammer to solve a small problem.  Issues are fantastic for searching against to see if someone had a similar problem.

**Comment by localhostdotdev** [comment]
maybe issues could be open for like a few hours, scrapped/archived and then closed again?

a scrapper for that wouldn't be hard, e.g. 

```
require 'open-uri'; (1..1200).each { |i| File.write("issue-#{i}.html", open("https://github.com/paper-trail-gem/paper_trail/issues/#{i}", allow_redirections: :safe).read) }
```

then upload the html files to a github repo and publish them as github pages, sounds easy

**Comment by jaredbeck** [comment]
The PT team has not reached a decision yet. Here's how you can help in the meantime:

1. My ideal solution would be a bot that automatically closes issues that don't follow the template. If you know how to help with that, PRs are welcome.
2. Please contact GH support and let them know that you'd like projects to have the option to show old issues, read-only.

**Comment by jaredbeck** [comment]
Issues are back, sorry for the inconvenience.

> My ideal solution would be a bot that automatically closes issues that don't follow the template.

I've written a [bot](https://github.com/paper-trail-gem/ptbot) that just comments on such issues. It doesn't close them, yet.

Please remember, due to limited volunteers, the [types of issues](https://github.com/paper-trail-gem/paper_trail/tree/master/.github/ISSUE_TEMPLATE) we can accept are severely limited compared to other projects. However, if you can *commit* to fixing a bug *yourself*, or building a new feature yourself, then please do open an issue and we'll help.

If you'd like to volunteer to triage issues, please email us.

**Pull request closed without merging**
