### PR TITLE
Support rails 6.0.0-alpha

### PR DESCRIPTION
**Pull request by iggant**
We are trying to test our application on rails 6.0.0.alpha but we can't install this because of the version lock
Probably this will be helpful that we can try and report any issues with edge rails

### CODE REVIEW

**Comment by jaredbeck** [comment]
Hi Anton,

I'm getting a lot of these warnings, which should be easy to fix:

```
DEPRECATION WARNING: update_attributes is deprecated and will be removed from Rails 6.1 (called from block (4 levels) in <top (required)> at /Users/jared/git/paper-trail-gem/paper_trail/spec/models/legacy_widget_spec.rb:9)
```

and some of these failures:

```
  1) Person#time_zone returns an ActiveSupport::TimeZone
     Failure/Error: super zone
     
     NoMethodError:
       super: no superclass method `time_zone=' for #<Person >
       Did you mean?  timeout
     # ./spec/dummy_app/app/models/person.rb:32:in `time_zone='
     # ./spec/models/person_spec.rb:12:in `block (3 levels) in <top (required)>'
```

Any ideas about `time_zone=`?

**Comment by iggant** [comment]
@jaredbeck I'll try to tackle this error at Wednesday

**Comment by iggant** [comment]
@jaredbeck with update_attributes should this be at the separate PR, or change it here?

**Comment by jaredbeck** [comment]
> @jaredbeck with update_attributes should this be at the separate PR, or change it here?

Either here or a *subsequent* PR is OK, thanks.

**Comment by iggant** [comment]
@jaredbeck this is very strange, because locally I don't have this errors. 
I'll continue on investigating this

**Comment by jaredbeck** [comment]
> @jaredbeck this is very strange, because locally I don't have this errors.

`CONTRIBUTING.md` describes how to run different rails versions, if that helps.

```
DB=sqlite bundle exec appraisal ar-6.0 rake
```

**Comment by iggant** [comment]
@jaredbeck  yes I tried this and for mysql everything is ok, but for sqlite not, 
I just add some puts inside, 
and as we can see for rails 5.2 we have: "#<Person id: nil, name: nil, time_zone: nil, mentor_id: nil>"
but for rails 6.0 it show        super: no superclass method `time_zone=' for #<Person > 

At the first variant we have attributes but at second doen't, 
And I don't find table persons in the db schema, where it is created?

**Comment by iggant** [comment]
@jaredbeck Please have a look I've finished with mysql, but I have to change serializer to Attribute API.  Please do code review if this is ok. And we can continue for Postgres

**Comment by jaredbeck** [comment]
> .. I've finished with mysql, but I [had] to change serializer to Attribute API.

This seems like a good use of the Attribute API, but I don't understand, is rails 6 dropping support for `serialize`? If so, can you link to a changelog entry or an issue that documents this? Thanks.

**Comment by jaredbeck** [comment]
Hi Anton, still working on this? Want me to keep it open?

**Comment by iggant** [comment]
@jaredbeck sorry was at vacation, still working on this

**Comment by Edouard-chin** [comment]
👋 @iggant, thanks for working on this. I'm also looking to get papertrail work on Rails 6.0.alpha to test our app on Rails edge. Let me know if I can be of any help to get this PR merged.

**Comment by jaredbeck** [comment]
> Let me know if I can be of any help ..

Please look at the CI failures if you have time, thanks!

**Comment by Edouard-chin** [comment]
The 2 failures on CI are related to Serializing Postgres arrays and were already fixed thanks to 4cce9b01794a403d07378f079337c9306acc74e1

The check to see if ActiveRecord version was `< 5.0.2` was incorrect

Applying this patch will make the tests pass.
```diff
diff --git a/lib/paper_trail/type_serializers/postgres_array_serializer.rb b/lib/paper_trail/type_serializers/postgres_array_serializer.rb
index b0c1247..e939646 100644
--- a/lib/paper_trail/type_serializers/postgres_array_serializer.rb
+++ b/lib/paper_trail/type_serializers/postgres_array_serializer.rb
@@ -29,8 +29,7 @@ module PaperTrail
       private

       def active_record_pre_502?
-        ::ActiveRecord::VERSION::MAJOR < 5 ||
-          (::ActiveRecord::VERSION::MINOR.zero? && ::ActiveRecord::VERSION::TINY < 2)
+        ::ActiveRecord.version < Gem::Version.new('5.0.2')
       end

       def serialize_with_ar(array)
```

**Comment by Edouard-chin** [comment]
Thanks, done in https://github.com/paper-trail-gem/paper_trail/pull/1172

**Comment by jaredbeck** [comment]
Closed by https://github.com/paper-trail-gem/paper_trail/pull/1172

**Pull request closed without merging**
