### PR TITLE
Warn if versions table pk is int but not bigint

### PR DESCRIPTION
**Pull request by jaredbeck**

### CODE REVIEW

**Comment by seanlinsley** [comment]
I'd be hesitant to make this change in my application, again b/c of disk usage. Theoretically it's simple doubling from 4 bytes to 8 bytes, but I'll need to test it on real data.

**Comment by jaredbeck** [comment]
> Theoretically it's a simple doubling from 4 bytes to 8 bytes, but I'll need to test it on real data.

Yeah. It'll also increase the size of any indexes that include that column.

**Comment by jaredbeck** [comment]
Sean, did you get a chance to test this out? Thanks.

**Comment by jaredbeck** [comment]
btw, [`bigint` is the default in rails as of 5.1](https://github.com/rails/rails/pull/26266), so new installs of PT are using `bigint`.

**Comment by jaredbeck** [comment]
@seanlinsley Can you review this weekend? Otherwise I think I'm just going to merge, seeing as this is the default in rails now.

**Comment by jaredbeck** [comment]
Thinking more about this, to do this right, I'd have to provide a config option so advanced users (`int` or `uuid`) can silence this warning, and I just don't want the complexity of another config option.

**Pull request closed without merging**
