### PR TITLE
Add compatibility with Rails 6.1

### LINKED ISSUE #1272: PaperTrail 11.0.0 is not compatible with ActiveRecord 6.1.0
**Is your feature suggestion related to a problem? Please describe.**

PaperTrail is currently untested against Rails 6.1.0 and emits a warning on startup:
```
      PaperTrail 11.0.0 is not compatible with ActiveRecord 6.1.0. We allow PT
      contributors to install incompatible versions of ActiveRecord, and this
      warning can be silenced with an environment variable, but this is a bad
      idea for normal use. Please install a compatible version of ActiveRecord
      instead (>= 5.2, < 6.1). Please see the discussion in paper_trail/compatibility.rb
      for details.
```

**Describe the solution you'd like to build**

- add ActiveRecord 6.1.0 to .travis.yml
- fix any observed incompatibilities
- update `ACTIVERECORD_LT` in `lib/paper_trail/compatibility.rb`

**Describe alternatives you've considered**

Ignore the warning. No regressions observed thus far.

### PR DESCRIPTION
**Pull request by sedubois**
Fixes #1272 

---

- [x] Wrote [good commit messages][1].
- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new 
  code introduces user-observable changes.
- [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by sedubois** [comment]
@jaredbeck how to trigger the Travis builds?

**Comment by pedrofurtado** [comment]
Happy to see this merged asap 🎉

**Comment by aried3r** [comment]
I'll have a look a this, thanks!

**Comment by sedubois** [comment]
Getting error:
```
An error occurred while loading spec_helper.
Failure/Error:
  ::ActiveRecord::MigrationContext.new(
    @migrations_path,
    ::ActiveRecord::Base.connection.schema_migration
  ).migrate
NameError:
  uninitialized constant ActiveRecord::MigrationContext
# ./spec/support/paper_trail_spec_migrator.rb:16:in `migrate'
# ./spec/spec_helper.rb:38:in `<top (required)>'
```

**Comment by sedubois** [comment]
@aried3r any idea what might cause this error?

**Comment by aried3r** [comment]
I believe `MigrationContext` is private API, as per https://github.com/rails/rails/pull/36439. `devise` and `derailed_benchmarks` seem to use some helpers for this, but neither have been updated for Rails 6.1 yet, so I'm not sure if that would work, since the constant cannot be found.

See also https://github.com/rails/rails/issues/36544.

I currently don't have time to look into this further myself.

**Comment by aried3r** [comment]
I should have checked better, paper_trail has a helper of that kind itself already.

https://github.com/paper-trail-gem/paper_trail/blob/f66c702c587160b1bef87d7086eb9018d6adf8a5/spec/support/paper_trail_spec_migrator.rb#L13-L25

From what I see it is still there https://github.com/rails/rails/blob/ddec53519e2c61665761e26d8c91a18724570b96/activerecord/lib/active_record/migration.rb#L1050.

This is just a wild guess, but _maybe_ it has to do with zeitwerk and the dummy app in the specs not yet compatible with it But again, just a guess.

**Comment by sedubois** [comment]
> maybe it has to do with zeitwerk

AFAIK zeitwerk is used since Rails 6.. Did Zeitwerk change in 6.1?

**Comment by aried3r** [comment]
Good news! https://github.com/rails/rails/pull/40806

I don't think this directly fixes our problem here, but at least this method will be officially supported, should it be merged and released.

> AFAIK zeitwerk is used since Rails 6. Did Zeitwerk change in 6.1?

Again, this is just a wild guess and maybe not worth going on a wild goose chase. But I tried to read up on it a bit more, it says zeitwerk is the default for Rails 6 applications. Our `dummy_app` here uses Rails 6[.1] in the spec, but I'm not sure if it's a fully upgraded Rails 6 application. In the sense, `rails app:update` wasn't called, we're not loading any framework defaults (`config.load_defaults`) etc, so I'm not sure in which state this dummy app is.

From the docs:

```Ruby
# config/application.rb

config.load_defaults 6.0
```

> enables zeitwerk autoloading mode on CRuby. In that mode, autoloading, reloading, and eager loading are managed by Zeitwerk.

https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#autoloading

I don't see what happens if you omit this line. My _assumption_ was, that with 6.1 the new defaults of 6.0 become the default, enabling zeitwerk. These are the settings for each version: https://guides.rubyonrails.org/configuring.html#results-of-config-load-defaults.

But, again, I'm not even sure it's that. Maybe shouldn't have mentioned it.

Does anyone here maybe have time to look into this locally some more? I'm currently busy at work with the last tickets before the winter holidays, so I cannot promise looking into it. But happy to review and discuss potential solutions.

**Comment by aried3r** [comment]
Ok, I was curious and tried it locally. Adding `require "active_record/migration"` on top of the `paper_trail_spec_migrator.rb` solves this issue (although I cannot tell you exactly why and when this changed).

However, then other tests start to fail, some of them being because we use Arel, which I believe is still private API. One example is:

```
  1) PaperTrail::Serializers::YAML.where_object constructs the correct WHERE query
     Failure/Error: expect(matches.right.val).to eq("%\narg1: Val 1\n%")

     NoMethodError:
       undefined method `val' for #<Arel::Nodes::Casted:0x00007fb99a4298d8>
       Did you mean?  value
     # ./spec/paper_trail/serializers/yaml_spec.rb:42:in `block (3 levels) in <module:Serializers>'
```

Indeed, `val` has been renamed to `value`: https://github.com/rails/rails/commit/280d6eb2e1663809aa7f743ed45abf5ef83cd5eb#diff-1c9b3a4b77db2a841dbe5b36ef9d63f7f9c646896944efdfd26c388396203c94

If you'd like to continue, these would need to be fixed for us to release a version compatible with Rails 6.1.

**Comment by jaredbeck** [comment]
@aried3r Good analysis. I've addressed many of the issues you found, in https://github.com/paper-trail-gem/paper_trail/pull/1274

@sedubois Please rebase this once #1274 is merged.

**Comment by jaredbeck** [comment]
@sedubois #1274 is merged, please rebase.

**Comment by pedrofurtado** [comment]
oh yeah 🏆

**Comment by jaredbeck** [comment]
> @sedubois #1274 is merged, please rebase.

Nevermind, I couldn't wait 😁 ; Closing via #1275, perserving @sedubois authorship. Thanks Sébastien for getting the ball rolling.

**Pull request closed without merging**
