### PR TITLE
Rails 6.1

### PR DESCRIPTION
**Pull request by jaredbeck**
Supersedes #1273, preserving @sedubois authorship.

### CODE REVIEW

**Review by aried3r — APPROVED** [review]
LGTM!

**Comment by aried3r** [comment]
Seeing how much waiting time there is with Travis these days for FLOSS projects, maybe we should consider switching to GitHub Actions at some point.

See these discussions from a different project for some reasons to make the switch and how a setup could look like for us (except we'd have a bit more setup and a bigger matrix due to different DBs):

https://github.com/shrinerb/content_disposition/pull/4#issuecomment-732498784
https://github.com/shrinerb/content_disposition/pull/6

**Comment by aried3r** [comment]
Hah, just saw you're already working on that: https://github.com/paper-trail-gem/paper_trail/compare/switch_ci_to_gha

Might I recommend `ruby/setup-ruby` over `actions/setup-ruby`? It does a lot of the heavy lifting and their generation of cache-keys is a bit more stable than what's (easily) possible with the official version. One example being, that it includes the OS version of the runner, like `ubuntu-18.04`, busting the cache once you switch to `ubuntu-20.04`. We've been bitten by this at work since native extensions of gem dependencies weren't being regenerated.

But whatever you choose, the switch is the important part and the fine tuning can be done incrementally.

https://github.com/ruby/setup-ruby

**Comment by jaredbeck** [comment]
> Seeing how much waiting time there is with Travis these days for FLOSS projects, maybe we should consider switching to GitHub Actions at some point.

I actually just emailed the other contributors about this, but didn't have your email address. Please email me so I can include you in that conversation.

Short story: travisci dot org is shutting down, there will be no free plan, and (pending other suggestions) I'm researching GH Actions on the `switch_ci_to_gha` (PRs into that branch welcome!)

**Pull request merged**
