### PR TITLE
refactor: remove unused generator

### PR DESCRIPTION
**Pull request by oicitrapdraz**
At least in my case all generator's operations falls in `generators/paper_trail/install/install_generator.rb`.

I don't see the use of this definition of `InstallGenerator` class.

### CODE REVIEW

**Comment by jaredbeck** [comment]
Hi Patricio. That's strange. Good find! Maybe it should have been deleted when `lib/generators/paper_trail/install/install_generator.rb` was created. Thanks.

**Comment by jaredbeck** [comment]
What should we do with `spec/generators/paper_trail/install_generator_spec.rb`? Move it to `spec/generators/install/install_generator_spec.rb`?

**Comment by oicitrapdraz** [comment]
If you are asking me, I would just delete it, but let's hear more opinions

**Comment by jaredbeck** [comment]
>> What should we do with spec/generators/paper_trail/install_generator_spec.rb?

> If you are asking me, I would just delete it ...

Why would you delete the spec?

**Comment by oicitrapdraz** [comment]
> Why would you delete the spec?

lol nevermind, I missread you.

**Comment by oicitrapdraz** [comment]
Then I think it is reasonable to move it, when I get home I'll make the commit.

**Comment by oicitrapdraz** [comment]
On second thought I think it makes more sense to move the generators inside the `lib/generators/paper_trail` folder (outside `install`), but anyway, I always ran into a problem (RSpec failed) after moving the files so I'll leave this branch clean (only with the first commit) and let you make the decision to accept the PR or not.

**Comment by jaredbeck** [comment]
> .. I always ran into a problem (RSpec failed) after moving the files ..

No worries, thanks for trying, and thanks for the contribution.

**Pull request merged**
