### PR TITLE
Use an app specific name for abstract version class to avoid autoloading conflict

### LINKED ISSUE #1320: Custom version classes documentation does not work with Rails eager autoloading
## Description

- [x] This is not a usage question, this is a bug report
- [x] This bug can be reproduced with the script I provide below
- [x] This bug can be reproduced in the latest release of the `paper_trail` gem

Current README paragraph [Custom version classes](https://github.com/paper-trail-gem/paper_trail#6a-custom-version-classes) does not eager load properly with Rails current usage of Zeitwerk. It produces the following log when starting the server in production mode 

```
Zeitwerk@rails.main: file [REDACTED]/app/models/paper_trail/version.rb is ignored because PaperTrail::Version is already defined
```

We detected this issue when method defined in this `app/models/paper_trail/version.rb` worked in development but not in production.
 
## Suggestion 

I envision two ways to solve this:

1. Set `abstract_class` on `PaperTrail::Version` in an initializer (however I'm not sure how to do it properly with autoloading)
2. Suggest a model with a different name like `ApplicationVersion` to inherit in your classes
```ruby
class PostVersion < ApplicationVersion
  # custom behaviour, e.g:
  self.table_name = :post_versions
end

# app/models/application_version.rb
class ApplicationVersion < ActiveRecord::Base
  include PaperTrail::VersionConcern
  self.abstract_class = true
end
```

## Script 

The following file should be put in `my_models/paper_trail` folder beside the script: 
```ruby
module PaperTrail
  class Version < ActiveRecord::Base
    include PaperTrail::VersionConcern
    self.abstract_class = true
  end
end
```

```ruby
# frozen_string_literal: true

# Use this template to report PaperTrail bugs.
# Please include only the minimum code necessary to reproduce your issue.
require "bundler/inline"

# STEP ONE: What versions are you using?
gemfile(true) do
  ruby "3.0.1"
  source "https://rubygems.org"
  gem "activerecord", "6.1.3.2"
  gem "paper_trail", "12.0.0", require: false
  gem "sqlite3", "1.4.2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Please use sqlite for your bug reports, if possible.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = nil
ActiveRecord::Schema.define do
  # STEP TWO: Define your tables here.
  create_table :users, force: true do |t|
    t.text :first_name, null: false
    t.timestamps null: false
  end

  create_table :user_versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.datetime :created_at
  end
end
ActiveRecord::Base.logger = Logger.new(STDOUT)
require "paper_trail"

require "zeitwerk"
loader = Zeitwerk::Loader.new
loader.push_dir('my_models')
loader.setup
loader.log!
loader.eager_load

puts "Eager loaded"

# STEP FOUR: Define your AR models here.
class UserVersion < PaperTrail::Version
  self.table_name = :user_versions
  self.sequence_name = :user_versions_id_seq
end

class User < ActiveRecord::Base
  has_paper_trail versions: {
    class_name: 'UserVersion'
  }
end

# STEP FIVE: Please write a test that demonstrates your issue.
class BugTest < ActiveSupport::TestCase
  def test_1
    assert PaperTrail::Version.abstract_class
  end
end

# STEP SIX: Run this script using `ruby my_bug_report.rb`
```

### PR DESCRIPTION
**Pull request by Hugo-Hache**
Thank you for your contribution!

Check the following boxes:

- [x] Wrote [good commit messages](http://chris.beams.io/posts/git-commit/).
- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [ ] Added tests.
- [ ] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new 
  code introduces user-observable changes.
- [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

Fix #1320

### CODE REVIEW

**Review by jaredbeck — CHANGES_REQUESTED** [review]
The paragraph above the proposed change should refer to `ApplicationRecord` instead, right?

```
If you only use custom version classes and don't have a `versions` table, you
must let ActiveRecord know that the `PaperTrail::Version` class is an
`abstract_class`.
```

Otherwise, it makes sense to me.

**Comment by Hugo-Hache** [comment]
> The paragraph above the proposed change should refer to the proposed `ApplicationVersion` instead, right?

The current paragraph is still valid, what we want to achieve is set the property abstract_class to true. Maybe I could append to it something like that ?

`A simple way to do that for all your custom versions classes is to create a parent ApplicationVersion class.`

**Comment by jaredbeck** [comment]
> A simple way to do that for all your custom versions classes is to create a parent ApplicationVersion class.

I like this sentence, let's add it. Also, how about amending the paragraph above with something like the following?

```diff
- you must let ActiveRecord know that the `PaperTrail::Version` 
- class is an `abstract_class`.
+ you must let ActiveRecord know that your base version 
+ class (eg. `ApplicationVersion` below) is an `abstract_class`.
```

**Comment by tlynam** [comment]
Hi @jaredbeck, how about I make these changes and we can merge this?

**Comment by jaredbeck** [comment]
Thanks Todd, go for it

**Comment by Hugo-Hache** [comment]
Mea culpa, took me an infinite time to handle this nice suggestion. Just updated it, let me know if it's ok for you.

**Review by tlynam — APPROVED** [review]
Looks great, thank you so much!

**Comment by Hugo-Hache** [comment]
Thanks @tlynam 👍 I hope I will be more reactive if you take interest in #1316

**Pull request merged**
