### PR TITLE
Improve reification of STI classes

### LINKED ISSUE #1332: Improve fetching reified class names for STI models
**Is your feature suggestion related to a problem? Please describe.**

We use PaperTrail on various models. One of them is a legacy model, where we use (abuse?) single table inheritance to separate callbacks, validations, and so forth into separate submodels. Let's call that model `Setting`, which has a column `name`. Name contains values such as `user_setting`, `team_setting`, and so on. 

We follow an approach similar to [the one outlined here](https://stackoverflow.com/a/23295546/2553104) to use STI using the names column to map underscored names (`user_setting`) to the actual class (`UserSetting`). Note that usually, STI columns  contain carmelized names.   

When destroying such a model and reifying it, the existing mechanism does not account for our  ̶a̶w̶e̶f̶u̶l̶ ̶h̶a̶c̶k̶ workaround, and we get an error: 

```ruby
setting = Setting.create(name: 'user_setting')
setting.destroy
setting.versions.last.reify # <- This fails with the wrong constant name 'user_setting'
```

The underlying issue is the implementation of `PaperTrails::Reifier`: 

```ruby
def version_reification_class(version, attrs)
  inheritance_column_name = version.item_type.constantize.inheritance_column
  inher_col_value = attrs[inheritance_column_name]
  class_name = inher_col_value.blank? ? version.item_type : inher_col_value
  class_name.constantize # <- This does not account for non-standard class names, such as underscored instead of camelized
end
```

**Describe the solution you'd like to build**

Instead of simply using `class_name.constantize` I suggest to take advantage of the mechanism Rails provides - calling `find_sti_class`: 

```ruby
def version_reification_class(version, attrs)
  clazz = version.item_type.constantize

  inheritance_column_name = clazz.inheritance_column
  inher_col_value = attrs[inheritance_column_name]
  return clazz if inher_col_value.blank?

  clazz.send(:find_sti_class, inher_col_value)
end
```

This allows users who use some non-standard form of STI to use PaperTrail, while keeping the existing functionality intact.

**Describe alternatives you've considered**

I realize that this is a _very_ specific problem to have. The obvious alternative is to just not have that problem and properly use STI. Unfortunately, we don't really have that option :shrug: 

I'm of course perfectly fine with just monkey-patching `PaperTrail::Reifier` to suit our needs. However, I can't see any obvious downside to using `find_sti_class`, and this change makes reifying more flexible. 

Let me know what you think :)

### PR DESCRIPTION
**Pull request by hschne**
Checklist

- [X] Wrote [good commit messages][1].
- [X] Feature branch is up-to-date with `master` (if not - rebase it).
- [X] Squashed related commits together.
- [X] Added tests.
- [X] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new 
  code introduces user-observable changes.
- [X] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
  
This fixes #1332. 

As discussed, two commits were created, one with failing test cases and one to fix them. Some details about this solution: 

I opted to add a new test model, rather than an modify an existing one (e.g. `Animal`) to better represent the specific edge case described in the issue. 

Futhermore, as `sti_class_for` was only added recently (Rails 6.1), reification falls back to calling the private method `find_sti_class`. I could not find another way to keep tests for older versions of Rails passing. 

I left the commits unsquashed for transparency, feel free to squash when merging.

### CODE REVIEW

**Review by jaredbeck — CHANGES_REQUESTED** [review]
This is an interesting STI feature that I had not heard of before. As of 6.1, it is a feature of Rails' public API, so I'm happy to support it.

Your [description of the issue](https://github.com/paper-trail-gem/paper_trail/issues/1332#issue-949506346) was excellent. Please boil that down into a few paragraphs, and add them to the comments above `#version_reification_class`.

**Comment by hschne** [comment]
I updated the comments, let me know what you think :)

**Review by jaredbeck — APPROVED** [review]

**Comment by jaredbeck** [comment]
Thanks Hans, nice work!

**Comment by jaredbeck** [comment]
Released in 12.1.0

**Pull request merged**
